name: Docker Build & Push

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Multi-Arch
        run: |
          VERSION=${{ github.ref_name }}
          IMAGE=ozimmermann/s3dns

          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t $IMAGE:latest \
            -t $IMAGE:$VERSION \
            . \
            --push

      - name: Update Docker Hub Description
        uses: peter-evans/dockerhub-description@v4.0.2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ozimmermann/s3dns
          readme-filepath: ./README.md